[package]
name = "pdla_json_to_markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.1" }
serde = { version = "1.0.210", features = ["derive"] }
clap = { version = "4.5.20", features = ["derive"] }
